services:
  app_1:
    image: nginx
    container_name: app_1
    volumes:
      - ./sites/app_1:/usr/share/nginx/html
    restart: always
    networks:
      - A
  app_2:
    image: nginx
    container_name: app_2
    volumes:
      - ./sites/app_2:/usr/share/nginx/html
    restart: always
    networks:
      - A
  proxy:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/nginx/ssl
    restart: always
    networks:
      - A
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
networks:
  A:
